title: ""
url: "https://friendshipkim.github.io"
baseurl: ""

markdown: kramdown
#ins_logo:
tracking_id: #

footer: yes
footer_url: "https://github.com/friendshipkim"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Projects"
   link: "projects"
